// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDA5x7MKrZ_d_ryFNijmAVSlHssieIeN-c',
    appId: '1:413103831633:web:fef5a2c24bbbc59bc85670',
    messagingSenderId: '413103831633',
    projectId: 'mis-labs-be234',
    authDomain: 'mis-labs-be234.firebaseapp.com',
    storageBucket: 'mis-labs-be234.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCox-p7bNXSY-tB18AyqUS9viy-hf1kQnA',
    appId: '1:413103831633:android:2420059fbeec798cc85670',
    messagingSenderId: '413103831633',
    projectId: 'mis-labs-be234',
    storageBucket: 'mis-labs-be234.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAVx4t1sZNpD3Nn3C86tfJk09Qhp_w34ok',
    appId: '1:413103831633:ios:1a0ac0c2256cc54ac85670',
    messagingSenderId: '413103831633',
    projectId: 'mis-labs-be234',
    storageBucket: 'mis-labs-be234.appspot.com',
    iosBundleId: 'com.example.misLab3',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAVx4t1sZNpD3Nn3C86tfJk09Qhp_w34ok',
    appId: '1:413103831633:ios:415c00234d20bd36c85670',
    messagingSenderId: '413103831633',
    projectId: 'mis-labs-be234',
    storageBucket: 'mis-labs-be234.appspot.com',
    iosBundleId: 'com.example.misLab3.RunnerTests',
  );
}
